---

# User and group of the user used to connect to the remote host
remote_user: "vagrant"

# Name of the local directory containing the required Red Hat binaries
local_rh_bin_dir: /opt/tools/jboss/bin

# Base directory for all binary files
base_repo_dir: /tmp/mw_repo

# Local directory containing all Java applications
app_dir: "{{ base_repo_dir }}/java_apps/bin"
# Local directory containing all CLI files
cli_dir: "{{ playbook_dir }}/files/cli"
# Local directory containing all installation binaries
bin_dir: "{{ base_repo_dir }}/rh_jboss_binaries"
# Local directory containing all golden images
gi_dir: "{{ base_repo_dir }}/rh_jboss_golden_images"


# Nexus connectivity information
nexus_user: "admin"
nexus_password: "admin123"
nexus_host: 192.168.0.100:8081
nexus_repository_id: "releases"

###### Default variables and their values

# Directory containing all downloaded artifacts on the remote host
#download_dir: '/tmp'

# Timezone for the hosts and the logs
#timezone: Europe/Berlin

# Used java version: Java 8 JDK. See recommendation https://access.redhat.com/solutions/18259
#java_pkg_name: java-1.8.0-openjdk-devel
