---
language: python
python: "2.7"

env:
  matrix:
    - ANSIBLE_VERSION=2.0.2.0
    - ANSIBLE_VERSION=2.1.1.0

install:
  - pip install ansible==$ANSIBLE_VERSION
  - ansible-galaxy install -r roles/requirements.yml -p ./roles
  - echo 'localhost' > inv

script:

  # Syntax check
  - ansible-playbook -i inv local.yml --syntax-check
  - ansible-playbook -i inv site.yml --syntax-check

  # List tasks
  - ansible-playbook -i inv local.yml --list-tasks
  - ansible-playbook -i inv site.yml --list-tasks
