---

# Setup the controller machine
- hosts: localhost
  connection: local
  roles:
    # Import necessary for the "download-binaries" role.
    - {role: "sabre1041.redhat-csp-download"}

    # Download the Red Hat software.
    - {role: "download-binaries"}

    # Create golden images.
    - {role: "golden-image"}

    # Build some sample applications.
    - {role: "java-demo-app"}
