---

- src: https://github.com/Maarc/ansible-role-redhat-jboss-common
  name: rh-jboss-common

- src: https://github.com/Maarc/ansible-role-redhat-jboss-eap
  name: rh-jboss-eap

- src: https://github.com/Maarc/ansible-role-redhat-jboss-web-server-tomcat
  name: rh-jboss-web-server-tomcat

- src: https://github.com/Maarc/ansible-role-redhat-jboss-web-server-httpd
  name: rh-jboss-web-server-httpd
