---

- hosts: "dev-jws-group"
  roles:
    # Red Hat JWS Tomcat instance
    - {role: "Maarc.rh-jboss-web-server-tomcat", app_list: { "tomcat-sample.war" }}
    # Red Hat JWS Apache instance
    - {role: "Maarc.rh-jboss-web-server-httpd"}

- hosts: "dev-eap-group"
  roles:
    - {
        # JBoss EAP 6 instance for the ticket-monster application
        role: "Maarc.rh-jboss-eap",
        jboss_eap_golden_image_name: "jboss-eap-6.4.11_GI",
        jboss_eap_instance_name: "ticket_monster",
        jboss_eap_instance_standalone_file: "standalone-full-ha.xml",
        jboss_eap_instance_port_offset: 0,
        app_list: { "ticket-monster.war" },
        cli_list: { "add_datasource.cli", "add_mod_cluster_6.cli"},
      }
    - {
        # JBoss EAP 7 instance for the petclinic application (note: toggle role and app to deploy from Nexus)
        role: "Maarc.rh-jboss-eap",
        jboss_eap_golden_image_name: "jboss-eap-7.0.3_GI",
        jboss_eap_instance_name: "petclinic",
        jboss_eap_instance_standalone_file: "standalone-full-ha.xml",
        jboss_eap_instance_port_offset: "1000",
        app_list: { "petclinic.war" },
        cli_list: { "add_datasource.cli", "add_mod_cluster_7.cli"},
        #app_mvn_list: [ { g: "com.redhat.jboss", a: "petclinic.war", v: "1.0", e: "war" } ],
      }
    - {
        # JBoss EAP 7 instance for the jenkins application
        role: "Maarc.rh-jboss-eap",
        jboss_eap_golden_image_name: "jboss-eap-7.0.3_GI",
        jboss_eap_instance_name: "jenkins",
        jboss_eap_instance_standalone_file: "standalone-full-ha.xml",
        jboss_eap_instance_port_offset: 2000,
        app_list: { "jenkins.war" },
        cli_list: { "add_datasource.cli", "add_mod_cluster_7.cli"},
      }
