---

- hosts: "dev-jws-group"
  roles:
    # Red Hat JWS Tomcat instance
    - {role: "rh_jboss_web_server__tomcat", app_list: { "bin/java_binaries/tomcat-sample.war" }, tags: ['jws_tomcat']}
    # Red Hat JWS Apache instance
    # - {role: "rh_jboss_web_server__apache",tags: ['jws_apache']}

- hosts: "dev-eap-group"
  roles:
    - {
        # JBoss EAP 7 instance for the ticket-monster application
        role: "rh_jboss_eap",
        jboss_eap_golden_image_name: "jboss-eap-7.0.0_GI",
        jboss_eap_instance_name: "ticket_monster",
        jboss_eap_instance_standalone_file: "standalone-full-ha.xml",
        jboss_eap_instance_port_offset: 0,
        app_list: { "bin/java_binaries/ticket-monster.war" },
        tags: ['tm']
      }
    - {
        # JBoss EAP 6 instance for the petclinic application (note: toggle role and app to deploy from Nexus)
        role: "rh_jboss_eap",
        jboss_eap_instance_name: "petclinic",
        jboss_eap_instance_standalone_file: "standalone.xml",
        jboss_eap_instance_port_offset: "1000",
        app_list: { "bin/java_binaries/petclinic.war" },
        #app_mvn_list: [ { g: "com.redhat.jboss", a: "petclinic.war", v: "1.0", e: "war" } ],
        tags: ['pc']
      }
    - {
        # JBoss EAP 7 instance for the jenkins application
        role: "rh_jboss_eap",
        jboss_eap_golden_image_name: "jboss-eap-7.0.0_GI",
        jboss_eap_instance_name: "jenkins",
        jboss_eap_instance_standalone_file: "standalone-full-ha.xml",
        jboss_eap_instance_port_offset: 2000,
        app_list: { "bin/java_binaries/jenkins.war" },
        tags: ['jk']
      }
