# Inspired from http://eduardsi.blogspot.de/2014/01/installing-nexus-with-ansible.html
# and from https://books.sonatype.com/nexus-book/3.0/reference/install.html#installation-archive
# Nexus OSS: http://www.sonatype.com/download-oss-sonatype
# This is installating Nexus v2 (access URL: http://hostname:8081/nexus/)

- hosts: nexus
  vars:
    nexus_download_url: http://www.sonatype.org/downloads/nexus-latest-bundle.tar.gz
    nexus_download_dest: /tmp/nexus-latest-bundle.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /opt/nexus

  tasks:

  - name: Install required RPM dependencies
    become: true
    yum: name={{ item }} state=present
    with_items:
     - unzip
     - wget
     - rsync
     - java-1.8.0-openjdk-devel
     - net-tools

  - name: Create "nexus" group
    become: true
    group: name="nexus" system="yes" state="present" gid="500"

  - name: Create "nexus" user
    become: true
    user: name="nexus" comment="nexus user" uid="500" group="nexus" shell="/bin/bash"

  - name: Download nexus
    get_url: url={{ nexus_download_url }} dest={{ nexus_download_dest }}
    register: nexus_download

  - name: Create {{ nexus_extracted_dir }} directory
    when: nexus_download.changed
    become: true
    file: path={{ nexus_extracted_dir }} state=directory owner=nexus group=nexus

  - name: Unpack nexus
    when: nexus_download.changed
    become: true
    unarchive: src={{  nexus_download_dest  }} dest={{ nexus_extracted_dir }} copy=no owner=nexus group=nexus

  - name: Move nexus to {{ nexus_dir }} directory
    when: nexus_download.changed
    become: true
    command: cp -af {{ nexus_extracted_dir }}/nexus-2.13.0-01/. {{ nexus_dir }}

  - name: Remove {{ nexus_extracted_dir }} directory
    when: nexus_download.changed
    become: true
    command: rm -rf {{ nexus_extracted_dir }}

  - name: Make {{ nexus_dir }} directory property of "nexus" user/group
    become: true
    file: path={{ nexus_dir }} group=nexus owner=nexus recurse=true

  - name: Make nexus runned by "nexus" user
    lineinfile: dest={{ nexus_dir }}/bin/nexus regexp="#RUN_AS_USER=" line="RUN_AS_USER=nexus" backrefs=true
    become: true

  - name: Set NEXUS_HOME
    become: true
    lineinfile: dest={{ nexus_dir }}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{ nexus_dir }}" backrefs=true

  - name: Create nexus piddir
    become: true
    file: path=/var/run/nexus state=directory group=nexus owner=nexus

  - name: Set nexus pidir
    become: true
    lineinfile: dest={{ nexus_dir }}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true

  - name: Set nexus working directory
    become: true
    lineinfile: dest={{ nexus_dir }}/conf/nexus.properties regexp="^nexus-work=" line="nexus-work=${bundleBasedir}/work/nexus"

  - name: Create systemd unit file
    become: true
    copy: owner=nexus group=nexus src="nexus.service" dest="/etc/systemd/system/nexus.service" mode="0755"
    register: nexus_service

  - name: Reload systemd
    when: nexus_service.changed
    become: true
    command: systemctl daemon-reload

  - name: Start Nexus
    become: true
    service: name="nexus" state="started" enabled="yes"
