# Inspired from http://eduardsi.blogspot.de/2014/01/installing-nexus-with-ansible.html
# and from https://books.sonatype.com/nexus-book/3.0/reference/install.html#installation-archive
# Nexus OSS: http://www.sonatype.com/download-oss-sonatype
# This is installating Nexus v3  (access URL: http://hostname:8081/)

- hosts: nexus
  vars:
    nexus_download_url: http://download.sonatype.com/nexus/3/nexus-3.0.0-03-unix.tar.gz
    nexus_download_dest: /tmp/nexus-latest-bundle.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /opt/nexus

  tasks:

  - name: Install required RPM dependencies
    become: true
    yum: name={{ item }} state=present
    with_items:
     - unzip
     - wget
     - rsync
     - java-1.8.0-openjdk-devel
     - net-tools

  - name: Create "nexus" group
    become: true
    group: name="nexus" system="yes" state="present" gid="500"

  - name: Create "nexus" user
    become: true
    user: name="nexus" comment="nexus user" uid="500" group="nexus" shell="/bin/bash"

  - name: Download nexus
    get_url: url={{ nexus_download_url }} dest={{ nexus_download_dest }}
    register: nexus_download

  - name: Create {{ nexus_extracted_dir }} directory
    when: nexus_download.changed
    become: true
    file: path={{ nexus_extracted_dir }} state=directory owner=nexus group=nexus

  - name: Unpack nexus
    when: nexus_download.changed
    become: true
    unarchive: src={{ nexus_download_dest }} dest={{ nexus_extracted_dir }} copy=no owner=nexus group=nexus

  - name: Move nexus to {{ nexus_dir }} directory
    when: nexus_download.changed
    become: true
    command: cp -af {{ nexus_extracted_dir }}/nexus-3.0.0-03/. {{ nexus_dir }}

  - name: Remove {{ nexus_extracted_dir }} directory
    when: nexus_download.changed
    become: true
    command: rm -rf {{ nexus_extracted_dir }}

  - name: Create systemd unit file
    become: true
    copy: owner=nexus group=nexus src="nexus.service" dest="/etc/systemd/system/nexus.service" mode="0755"
    register: nexus_service

  - name: Reload systemd
    when: nexus_service.changed
    become: true
    command: systemctl daemon-reload

  - name: Start Nexus
    become: true
    service: name="nexus" state="started" enabled="yes"
