# Note: no port forwarding is needed when using a private network. The VMs are reacheable directly.

name=''

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  {
    'host-dev-01' => '101',
    'host-dev-02' => '102',
    'host-dev-03' => '103',
  }.each do |short_name, id|
    config.vm.define short_name do |host|
      name = short_name
      host.vm.network 'private_network', ip: '192.168.0.'+id
      host.vm.hostname = short_name
      host.vm.network :forwarded_port, guest: 22, host: '2'+id, id: "ssh"
    end
  end

  # Nexus 2.13 instead of 3 as currently recommended by Sonatype
  config.vm.define 'nexus', primary: false do |host|
    name = 'nexus'
    host.vm.hostname = 'nexus'
    host.vm.network "private_network", ip: '192.168.0.100'
    host.vm.network :forwarded_port, guest: 22, host: 2100, id: "ssh"
    host.vm.provision "ansible" do |ansible|
      ansible.playbook = "nexus/nexus_2.13.yml"
    end
  end

  config.vm.define 'tower', primary: false do |host|
    config.vm.box = "ansible/tower"
    name = 'tower'
    host.vm.hostname = 'tower';
    host.vm.network "private_network", ip: '192.168.0.200'
    host.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"
    host.vm.synced_folder "/tmp/mw_repo", "/tmp/mw_repo", create: true, group: "awx", owner: "awx"
    host.vm.provision "ansible" do |ansible|
      ansible.playbook = "tower/tower.yml"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = name
    # 33% of the CPU from the host
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "33"]
    # 2048 MB RAM
    vb.memory = 2048
  end

end
