---

- name: (02) JWS Tomcat configure admin user
  template:
    owner: "{{ jws_tomcat.user }}"
    group: "{{ jws_tomcat.group }}"
    src: tomcat-users.xml.j2
    dest: "{{ jws_tomcat.home}}/conf/tomcat-users.xml"
    mode: "755"
  notify: Restart JWS Tomcat

- name: (02) Set JWS Tomcat HTTP port ({{ jws_tomcat.port_http }})
  replace:
    dest: "{{ jws_tomcat.home}}/conf/server.xml"
    regexp: '^(.*)port="([0-9]*)" protocol="HTTP/1.1"(.*)$'
    replace: "\\1port=\"{{ jws_tomcat.port_http }}\" protocol=\"HTTP/1.1\"\\3"
  notify: Restart JWS Tomcat

- name: (02) Set JWS Tomcat AJP port ({{ jws_tomcat.port_ajp }})
  replace:
    dest: "{{ jws_tomcat.home}}/conf/server.xml"
    regexp: '^(.*)port="([0-9]*)" protocol="AJP/1.3"(.*)$'
    replace: "\\1port=\"{{ jws_tomcat.port_ajp }}\" protocol=\"AJP/1.3\"\\3"
  notify: Restart JWS Tomcat

- name: (02) Set JWS Tomcat HTTPS port ({{ jws_tomcat.port_https }})
  replace:
    dest: "{{ jws_tomcat.home}}/conf/server.xml"
    regexp: '^(.*)redirectPort="([0-9]*)"(.*)$'
    replace: "\\1redirectPort=\"{{ jws_tomcat.port_https }}\"\\3"
  notify: Restart JWS Tomcat
