---

- name: (04) Copy the application(s)
  become: true
  copy:
    owner: "{{ jws_tomcat.user }}"
    group: "{{ jws_tomcat.group }}"
    src: "{{ item }}"
    dest: "{{ jws_tomcat.deployment_dir }}"
  with_items: "{{ app_list }}"
  notify: Restart JWS Tomcat
