---

# Installation following: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Server/3/html/Installation_Guide/sect-ZIP_Installation.html
# ... and  https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-centos-7

#### Create user(s)
- include: 00__prepare.yml
  become: true

#### Copy binaries
- include: 01__copy_and_unpack.yml
  become: true

#### Configure JWS
- include: 02__configure.yml
  become: true

#### Create Service Account
- include: 03__register_service.yml
  become: true

#### Deploy applications
- include: 04__deploy_applications.yml
  become: true

#### Start JWS
- name: (99) Ensure JWS Tomcat is running
  become: true
  service:
    name: "{{ jws_tomcat.service }}"
    state: started
    enabled: yes
  register: jws_tomcat_start
