---

- name: (05) Copy the application(s)
  become: true
  copy:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: "{{ item }}"
    dest: "{{ jboss_eap_instance_deployment_dir }}"
  with_items: "{{ app_list }}"

  #notify: Restart JBoss EAP

- name: (99) Ensure JBoss EAP is running ("{{ jboss_eap_instance_service_name }}")
  become: true
  service:
    name: "{{ jboss_eap_instance_service_name }}"
    state: started
    enabled: yes
  register: jboss_eap_started
