---

- name: (05) Replicate the buttler
  become: true
  copy:
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "bin/java_binaries/jenkins.war"
      dest: "{{ jboss_eap_instance_deployment_dir }}"
  notify: Restart JBoss EAP

- name: (99) Ensure JBoss EAP is running
  become: true
  service:
    name: "{{ jboss_eap_instance_service_name }}"
    state: started
    enabled: yes
  register: jboss_eap_started
