---

#### Create the dedicated JBoss EAP user and group

- name: "(00) Create \"{{ jboss_eap_group }}\" group for JBoss EAP"
  become: true
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "{{ jboss_eap_group_id }}"

- name: "(00) Create \"{{ jboss_eap_user }}\" user for JBoss EAP"
  become: true
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "{{ jboss_eap_group_id }}"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_user_home }}"
    shell: "/bin/bash"

- name: (00) Create .bashrc file for JBoss EAP user
  become: true
  template:
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
    src: .bashrc.j2
    dest: "{{ jboss_eap_user_home }}/.bashrc"
    mode: "644"
