---

- name: (00) Check "jboss_eap_instance_name" variable
  fail: msg="This role requires jboss_eap_instance_name to be set and non empty."
  when: jboss_eap_instance_name is not defined or jboss_eap_instance_name == ''

- name: (00) Check "jboss_eap_golden_image_name" variable
  fail: msg="This role requires jboss_eap_golden_image_name to be set and non empty."
  when: jboss_eap_golden_image_name is not defined or jboss_eap_golden_image_name == ''

- name: (00) Check "bin_dir" variable
  fail: msg="This role requires bin_dir to be set and non empty."
  when: bin_dir is not defined or bin_dir == ''

- name: (00) Check "gi_dir" variable
  fail: msg="This role requires gi_dir to be set and non empty."
  when: gi_dir is not defined or gi_dir == ''

- name: "{{ jboss_eap_instance_name }} (00) Create groups for EAP"
  group:
    name: "{{ item.group }}"
    system: yes
    state: present
    gid: "{{ item.group_id }}"
  with_items:
    - "{{ jboss }}"

- name: "{{ jboss_eap_instance_name }} (00) Create users for EAP"
  user:
    name: "{{ item.user }}"
    comment: "{{ item.user }} user"
    uid: "{{ item.group_id }}"
    group: "{{ item.group }}"
    home: "{{ item.user_home }}"
    shell: "/bin/sh"
  with_items:
    - "{{ jboss }}"

- name: "{{ jboss_eap_instance_name }} (00) Create .bashrc file for the EAP user"
  template:
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    src: .bashrc.j2
    dest: "{{ item.user_home }}/.bashrc"
    mode: "644"
  with_items:
    - "{{ jboss }}"
