---

- name: (01) Check existence of an installation
  become: true
  stat:
    path: "{{ jboss_eap_home + '/version.txt'}}"
  register: jboss_eap_exists

- name: (01) Copy zipped JBoss EAP distribution
  copy:
    src: "{{ jboss_eap_zip_artifact_dir + '/' + jboss_eap_zip_artifact_name + '.zip' }}"
    dest: "{{ jboss_eap_zip_artifact_dl_dest }}"
  register: copy_zip_state

- name: (01) Extract JBoss EAP zipped distribution
  # new version or no installation so far
  when: jboss_eap_exists.stat.exists == false or copy_zip_state.changed == true
  become: true
  unarchive:
    src: "{{ jboss_eap_zip_artifact_dl_dest }}"
    dest: "{{ jboss_eap_user_home }}"
    copy: no
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
  #notify: Restart JBoss EAP
