---

- name: "{{ jboss_eap_instance_name }} {{ info }} Check existence of the target dir ({{ target_dir }})"
  stat:
    path: "{{ target_dir }}"
  register: conf_00

# Initial creation of the standalone directory
- block:

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy the JBoss EAP standalone directory "
    command: "cp -Rfp {{ jboss_home }}/standalone {{ target_dir }}"
    register: conf_01

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy instance specific standalone.conf"
    copy:
      remote_src: true
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      src: "{{ jboss_home }}/bin/standalone.conf"
      dest: "{{ target_dir }}/configuration/standalone.conf"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Create the service directory"
    file:
      path: "{{ target_dir }}/service"
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      state: directory
      mode: "755"

  - name: "{{ jboss_eap_instance_name }} {{ info }} Copy init.d script (jboss-as-standalone.sh)"
    copy:
      remote_src: true
      owner: "{{ jboss.user }}"
      group: "{{ jboss.group }}"
      src: "{{ jboss_home }}/bin/init.d/jboss-as-standalone.sh"
      dest: "{{ target_dir }}/service/jboss-as-standalone.sh"
      mode: "755"

  when: conf_00.stat.isdir is undefined or conf_00.stat.isdir == False

- name: "{{ jboss_eap_instance_name }} {{ info }} Update service init.d script (jboss-as-standalone.sh)"
  lineinfile:
    dest: "{{ target_dir }}/service/jboss-as-standalone.sh"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    # Setting the correct JBOSS_CONF file
    - { regexp: '^(.*)JBOSS_CONF=(.*)$', line: "\\1JBOSS_CONF=\"{{ jboss_eap_instance_dir }}/service/jboss-as.conf\"" }
    # Setting the correct jboss.server.base.dir
    - { regexp:  '(.*)JBOSS_SCRIPT=(.*)standalone.sh$', line: "\\1JBOSS_SCRIPT=\"\\2standalone.sh -Djboss.server.base.dir={{ jboss_eap_instance_dir }}\"" }
    # Specific to the reload mechanism of JBoss EAP 6 - Changing the "JBOSS_CONSOLE_LOG" to "JBOSS_SERVER_LOG" (prevents hanging at startup while the console log has been disabled)
    - { regexp: '^(.*)JBAS015874(.*)\$JBOSS_CONSOLE_LOG(.*)$', line: "\\1JBAS015874\\2{{ jboss_eap_instance_dir }}/log/server.log\\3" }
    # Specific to the reload mechanism of JBoss EAP 7 - Set the startup-marker file to the instance specific folder
    - { regexp: '^(.*)\$JBOSS_HOME/standalone/tmp/startup-marker(.*)$', line: "\\1{{ jboss_eap_instance_dir }}/tmp/startup-marker\\2" }
  register: conf_02

- name: "{{ jboss_eap_instance_name }} {{ info }} Generate service jboss-as.conf"
  template:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: jboss-as.conf.j2
    dest: "{{ target_dir }}/service/jboss-as.conf"
    mode: "755"
  register: conf_03

- name: "{{ jboss_eap_instance_name }} {{ info }} Update standalone.conf (1/2)"
  lineinfile:
    dest: "{{ target_dir }}/configuration/standalone.conf"
    line: "{{ item }}"
  with_items:
    # Set default binding address
    - "JAVA_OPTS=\"$JAVA_OPTS -Djboss.bind.address={{ jboss_eap_bind_ip_address_public }}\""
    # Set management binding address
    - "JAVA_OPTS=\"$JAVA_OPTS -Djboss.bind.address.management={{ jboss_eap_bind_ip_address_management }}\""
    # Set port offset and time zone
    - "JAVA_OPTS=\"$JAVA_OPTS -Duser.timezone={{ timezone }} -Djboss.socket.binding.port-offset={{ jboss_eap_instance_port_offset }}\""
    # Set node name
    - "JAVA_OPTS=\"$JAVA_OPTS -Djboss.node.name={{ ansible_hostname }}__{{ jboss_eap_instance_name }}\""
  register: conf_04

- name: "{{ jboss_eap_instance_name }} {{ info }} Update standalone.conf (2/2)"
  lineinfile:
    dest: "{{ target_dir }}/configuration/standalone.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    # Set JVM Xms
    - { regexp: '^(.*)Xms(\d+)m(.*)$', line: "\\1Xms{{ jvm_xm }}m\\3" }
    # Set JVM Xms
    - { regexp: '^(.*)Xmx(\d+)m(.*)$', line: "\\1Xmx{{ jvm_xm }}m\\3" }
    # Remove JVM MaxPermSize
    - { regexp: '^(.*) -XX:MaxPermSize=(\d+)m(.*)$', line: "\\1\\3" }
  register: conf_05

- name: "{{ jboss_eap_instance_name }} {{ info }} Copy application(s) from the file system"
  copy:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: "{{ item }}"
    dest: "{{ target_dir }}/deployments"
  with_items: "{{ app_list }}"
  register: conf_06

- name: "{{ jboss_eap_instance_name }} {{ info }} Retrieve application(s) from Nexus"
  maven_artifact: group_id={{ item.g }} artifact_id={{ item.a }} extension={{ item.e }} version={{ item.v }} repository_url={{ nexus_download_url }} dest={{ download_dir }}/{{ item.g }}_{{ item.a }}_{{ item.e }}_{{ item.v }} username="{{ nexus_user }}" password="{{ nexus_password }}"
  with_items: "{{ app_mvn_list }}"
  register: conf_07

- name: "{{ jboss_eap_instance_name }} {{ info }} Copy application(s) from Nexus"
  when: conf_07.changed
  copy:
    remote_src: true
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: "{{ download_dir }}/{{ item.g }}_{{ item.a }}_{{ item.e }}_{{ item.v }}"
    dest: "{{ target_dir }}/deployments/{{ item.a }}"
  with_items: "{{ app_mvn_list }}"

- name: "{{ jboss_eap_instance_name }} {{ info }} Generate service systemd unit file"
  template:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: jboss-as-standalone.service.j2
    dest: "{{ target_dir }}/service/{{ jboss_eap_instance_service_name }}.service"
    mode: "755"
  register: conf_08

- name: "{{ jboss_eap_instance_name }} {{ info }} Generate instance.info file"
  template:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: instance.info.j2
    dest: "{{ target_dir }}/instance.info"
    mode: "644"
  register: conf_09

- name: "{{ jboss_eap_instance_name }} {{ info }} Update mgmt-*.properties"
  lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
  with_items:
    - { dest: "{{ target_dir }}/configuration/mgmt-users.properties", line: '# user: redhat password: redhat123!' }
    - { dest: "{{ target_dir }}/configuration/mgmt-users.properties", line: 'redhat=ba2caa9378fa898f1dea88804abe52b4' }
    - { dest: "{{ target_dir }}/configuration/mgmt-groups.properties", line: 'redhat=' }
  register: conf_10

- name: "{{ jboss_eap_instance_name }} {{ info }} Set is_modified"
  set_fact:
    is_modified: conf_01.changed or conf_02.changed or conf_03.changed or conf_04.changed or conf_05.changed or conf_06.changed or conf_07.changed or conf_08.changed or conf_09.changed or conf_10.changed
