---

- name: "{{ jboss_eap_instance_name }} (03) Directly copy application(s)"
  become: true
  copy:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: "{{ item }}"
    dest: "{{ jboss_eap_instance_deployment_dir }}"
  with_items: "{{ app_list }}"
  #notify: Restart JBoss EAP

- name: "{{ jboss_eap_instance_name }} (03) Retrieve application from Nexus"
  maven_artifact: group_id={{ item.g }} artifact_id={{ item.a }} extension={{ item.e }} version={{ item.v }} repository_url={{ nexus_download_url }} dest={{ download_dir }}/{{ item.a }} username="{{ nexus_user }}" password="{{ nexus_password }}"
  with_items: "{{ app_mvn_list }}"
  register: app_nexus

- name: "{{ jboss_eap_instance_name }} (03) Copy the application to the deployment directory"
  when: app_nexus.changed == True
  become: true
  copy:
    remote_src: true
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: "{{ download_dir }}/{{ item.a }}"
    dest: "{{ jboss_eap_instance_deployment_dir }}/{{ item.a }}"
  with_items: "{{ app_mvn_list }}"
  #notify: Restart JBoss EAP
