---

#### Create user
- include: 00__prepare.yml
  become: true

#### Copy binaries
- include: 01__copy_and_unpack.yml
  become: true

#### Configure EAP
- include: 02__configure.yml
  become: true

#### Provision configuration and applications 
- include: 03__provision.yml
  become: true

#### Create Service Account
- include: 04__register_service.yml
  become: true
