---

- name: (00) Install Java and basic RPM dependencies
  become: true
  yum: name={{ item }} state=present
  with_items:
   - unzip
   - "{{ java_pkg_name }}"
   - rsync
   # for netstat
   - net-tools
   # for pstree
   - psmisc

# Set in the DEV environment during the first setup
- name: (00) {dev} Copy .bashrc
  when: env == "dev"
  template:
    src: .bashrc.j2
    dest: "/home/{{ remote_user }}/.bashrc"
    owner: "{{ remote_user }}"
  register: bashrc_uploaded

# Set in the DEV environment during the first setup
- name: (00) {dev} Set server timezone
  become: true
  when: bashrc_uploaded.changed == True and env == "dev"
  command: "timedatectl set-timezone {{ timezone }}"
